name: g86
version: 0.2.0
synopsis: G86 encoding.
author: Galen Huntington <galen@alumni.reed.edu>
license: MIT
category: Codec

source-dirs:
   - .

library: {}

executable:
   main: main.hs
   dependencies:
      - split >= 0.2 && < 0.3

dependencies:
   - base >= 4.9 && < 5
   - bytestring >= 0.10 && < 0.12
   - vector >= 0.12 && < 0.14

tests:
   suite:
      main: test.hs
      dependencies:
         - QuickCheck >= 2.12.6.1

